# processing voltage area: top_riscv_soc/PD_CORE
set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 1324.200 -nets VDD_1V8 -layer METTP -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 918.100 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 577.760 -nets VDD_1V8 -layer METTP -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 189.420 -start_high_ends coordinate  -start_high_ends_coordinate 931.540 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 195.240 -nets VDD_1V8 -layer METTP -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 189.420 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1458.940 -nets VDD_1V8 -layer METTPL -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 1330.920 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 924.820 -nets VDD_1V8 -layer METTPL -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 571.040 -start_high_ends coordinate  -start_high_ends_coordinate 1330.920 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 196.140 -nets VDD_1V8 -layer METTPL -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 584.480 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1306.280 -nets VSS -layer METTP -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 936.020 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 559.840 -nets VSS -layer METTP -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 207.340 -start_high_ends coordinate  -start_high_ends_coordinate 949.460 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 213.160 -nets VSS -layer METTP -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 207.340 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1441.020 -nets VSS -layer METTPL -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 1313.000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 942.740 -nets VSS -layer METTPL -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 553.120 -start_high_ends coordinate  -start_high_ends_coordinate 1313.000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 214.060 -nets VSS -layer METTPL -width 13.440 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 566.560 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal5 straps for net VDD_1V8
create_power_straps  -direction horizontal  -start_at 319.975 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 189.420 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 418.535 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 189.420 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 517.095 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 189.420 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 615.655 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 918.100 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 714.215 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 918.100 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 812.775 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 918.100 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 911.335 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 918.100 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1000.935 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 918.100 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1099.495 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 918.100 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1198.055 -nets VDD_1V8  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 918.100 -start_high_ends coordinate  -start_high_ends_coordinate 1465.660 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 330.355 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 207.340 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 428.915 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 207.340 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 527.475 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 207.340 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 626.035 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 936.020 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 724.595 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 936.020 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 823.155 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 936.020 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 921.715 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 936.020 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1011.315 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 936.020 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1109.875 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 936.020 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1208.435 -nets VSS  -layer METTP -width 1.680 -pitch_within_group 97.330 -start_low_ends coordinate  -start_low_ends_coordinate 936.020 -start_high_ends coordinate  -start_high_ends_coordinate 1447.740 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VDD_1V8
create_power_straps  -direction vertical  -start_at 328.480 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 584.480 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 440.480 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 584.480 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 552.480 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 584.480 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 658.880 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 584.480 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 770.880 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 584.480 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 877.280 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 584.480 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 989.280 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 1330.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1095.680 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 1330.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1207.680 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 1330.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1314.080 -nets VDD_1V8  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 188.520 -start_high_ends coordinate  -start_high_ends_coordinate 1330.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 335.960 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 566.560 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 447.960 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 566.560 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 559.960 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 566.560 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 666.360 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 566.560 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 778.360 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 566.560 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 884.760 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 566.560 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 996.760 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 1313.000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1103.160 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 1313.000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1215.160 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 1313.000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1321.560 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 109.500 -start_low_ends coordinate  -start_low_ends_coordinate 206.440 -start_high_ends coordinate  -start_high_ends_coordinate 1313.000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false

