###################################################################

# Created by write_sdc on Tue Oct  2 12:50:32 2018

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current uA
set_operating_conditions TYPICAL -library D_CELLS_HDLL_LPMOS_typ_1_80V_25C
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports reset_pad]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports MISO_pad]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports RX_UART_pad]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports maip_pad]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports MOSI_pad]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports SCLK_pad]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports SCS_pad]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports TX_UART_pad]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports {gpio_pad[7]}]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports {gpio_pad[6]}]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports {gpio_pad[5]}]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports {gpio_pad[4]}]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports {gpio_pad[3]}]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports {gpio_pad[2]}]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports {gpio_pad[1]}]
set_driving_cell -lib_cell ICF -library                                        \
IO_CELLS_F3V_LPMOS_UPF_typ_1_80V_3_30V_25C [get_ports {gpio_pad[0]}]
set_load -pin_load 0.02433 [get_ports MOSI_pad]
set_load -pin_load 0.02433 [get_ports SCLK_pad]
set_load -pin_load 0.02433 [get_ports SCS_pad]
set_load -pin_load 0.02433 [get_ports TX_UART_pad]
set_load -pin_load 0.02433 [get_ports {gpio_pad[7]}]
set_load -pin_load 0.02433 [get_ports {gpio_pad[6]}]
set_load -pin_load 0.02433 [get_ports {gpio_pad[5]}]
set_load -pin_load 0.02433 [get_ports {gpio_pad[4]}]
set_load -pin_load 0.02433 [get_ports {gpio_pad[3]}]
set_load -pin_load 0.02433 [get_ports {gpio_pad[2]}]
set_load -pin_load 0.02433 [get_ports {gpio_pad[1]}]
set_load -pin_load 0.02433 [get_ports {gpio_pad[0]}]
set_max_capacitance 0.09887 [get_ports reset_pad]
set_max_capacitance 0.09887 [get_ports MISO_pad]
set_max_capacitance 0.09887 [get_ports RX_UART_pad]
set_max_capacitance 0.09887 [get_ports maip_pad]
set_max_capacitance 0.09887 [get_ports MOSI_pad]
set_max_capacitance 0.09887 [get_ports SCLK_pad]
set_max_capacitance 0.09887 [get_ports SCS_pad]
set_max_capacitance 0.09887 [get_ports TX_UART_pad]
set_max_capacitance 0.09887 [get_ports {gpio_pad[7]}]
set_max_capacitance 0.09887 [get_ports {gpio_pad[6]}]
set_max_capacitance 0.09887 [get_ports {gpio_pad[5]}]
set_max_capacitance 0.09887 [get_ports {gpio_pad[4]}]
set_max_capacitance 0.09887 [get_ports {gpio_pad[3]}]
set_max_capacitance 0.09887 [get_ports {gpio_pad[2]}]
set_max_capacitance 0.09887 [get_ports {gpio_pad[1]}]
set_max_capacitance 0.09887 [get_ports {gpio_pad[0]}]
set_max_transition 1.42597 [get_ports reset_pad]
set_max_transition 1.42597 [get_ports MISO_pad]
set_max_transition 1.42597 [get_ports RX_UART_pad]
set_max_transition 1.42597 [get_ports maip_pad]
set_max_transition 1.42597 [get_ports MOSI_pad]
set_max_transition 1.42597 [get_ports SCLK_pad]
set_max_transition 1.42597 [get_ports SCS_pad]
set_max_transition 1.42597 [get_ports TX_UART_pad]
set_max_transition 1.42597 [get_ports {gpio_pad[7]}]
set_max_transition 1.42597 [get_ports {gpio_pad[6]}]
set_max_transition 1.42597 [get_ports {gpio_pad[5]}]
set_max_transition 1.42597 [get_ports {gpio_pad[4]}]
set_max_transition 1.42597 [get_ports {gpio_pad[3]}]
set_max_transition 1.42597 [get_ports {gpio_pad[2]}]
set_max_transition 1.42597 [get_ports {gpio_pad[1]}]
set_max_transition 1.42597 [get_ports {gpio_pad[0]}]
create_clock [get_ports clk_pad]  -name CLK  -period 50  -waveform {0 25}
set_clock_latency 1  [get_clocks CLK]
set_clock_uncertainty 0.1  [get_clocks CLK]
set_clock_transition -min -fall 0.05 [get_clocks CLK]
set_clock_transition -min -rise 0.05 [get_clocks CLK]
set_clock_transition -max -fall 0.05 [get_clocks CLK]
set_clock_transition -max -rise 0.05 [get_clocks CLK]
set_input_delay -clock CLK  -max 20  [get_ports reset_pad]
set_input_delay -clock CLK  -min 0.1  [get_ports reset_pad]
set_input_delay -clock CLK  -max 20  [get_ports MISO_pad]
set_input_delay -clock CLK  -min 0.1  [get_ports MISO_pad]
set_input_delay -clock CLK  -max 20  [get_ports RX_UART_pad]
set_input_delay -clock CLK  -min 0.1  [get_ports RX_UART_pad]
set_input_delay -clock CLK  -max 20  [get_ports maip_pad]
set_input_delay -clock CLK  -min 0.1  [get_ports maip_pad]
set_input_delay -clock CLK  -max 20  [get_ports MOSI_pad]
set_input_delay -clock CLK  -min 0.1  [get_ports MOSI_pad]
set_input_delay -clock CLK  -max 20  [get_ports SCLK_pad]
set_input_delay -clock CLK  -min 0.1  [get_ports SCLK_pad]
set_input_delay -clock CLK  -max 20  [get_ports SCS_pad]
set_input_delay -clock CLK  -min 0.1  [get_ports SCS_pad]
set_input_delay -clock CLK  -max 20  [get_ports TX_UART_pad]
set_input_delay -clock CLK  -min 0.1  [get_ports TX_UART_pad]
set_input_delay -clock CLK  -max 20  [get_ports {gpio_pad[7]}]
set_input_delay -clock CLK  -min 0.1  [get_ports {gpio_pad[7]}]
set_input_delay -clock CLK  -max 20  [get_ports {gpio_pad[6]}]
set_input_delay -clock CLK  -min 0.1  [get_ports {gpio_pad[6]}]
set_input_delay -clock CLK  -max 20  [get_ports {gpio_pad[5]}]
set_input_delay -clock CLK  -min 0.1  [get_ports {gpio_pad[5]}]
set_input_delay -clock CLK  -max 20  [get_ports {gpio_pad[4]}]
set_input_delay -clock CLK  -min 0.1  [get_ports {gpio_pad[4]}]
set_input_delay -clock CLK  -max 20  [get_ports {gpio_pad[3]}]
set_input_delay -clock CLK  -min 0.1  [get_ports {gpio_pad[3]}]
set_input_delay -clock CLK  -max 20  [get_ports {gpio_pad[2]}]
set_input_delay -clock CLK  -min 0.1  [get_ports {gpio_pad[2]}]
set_input_delay -clock CLK  -max 20  [get_ports {gpio_pad[1]}]
set_input_delay -clock CLK  -min 0.1  [get_ports {gpio_pad[1]}]
set_input_delay -clock CLK  -max 20  [get_ports {gpio_pad[0]}]
set_input_delay -clock CLK  -min 0.1  [get_ports {gpio_pad[0]}]
set_output_delay -clock CLK  -max 20  [get_ports MOSI_pad]
set_output_delay -clock CLK  -min -0.1  [get_ports MOSI_pad]
set_output_delay -clock CLK  -max 20  [get_ports SCLK_pad]
set_output_delay -clock CLK  -min -0.1  [get_ports SCLK_pad]
set_output_delay -clock CLK  -max 20  [get_ports SCS_pad]
set_output_delay -clock CLK  -min -0.1  [get_ports SCS_pad]
set_output_delay -clock CLK  -max 20  [get_ports TX_UART_pad]
set_output_delay -clock CLK  -min -0.1  [get_ports TX_UART_pad]
set_output_delay -clock CLK  -max 20  [get_ports {gpio_pad[7]}]
set_output_delay -clock CLK  -min -0.1  [get_ports {gpio_pad[7]}]
set_output_delay -clock CLK  -max 20  [get_ports {gpio_pad[6]}]
set_output_delay -clock CLK  -min -0.1  [get_ports {gpio_pad[6]}]
set_output_delay -clock CLK  -max 20  [get_ports {gpio_pad[5]}]
set_output_delay -clock CLK  -min -0.1  [get_ports {gpio_pad[5]}]
set_output_delay -clock CLK  -max 20  [get_ports {gpio_pad[4]}]
set_output_delay -clock CLK  -min -0.1  [get_ports {gpio_pad[4]}]
set_output_delay -clock CLK  -max 20  [get_ports {gpio_pad[3]}]
set_output_delay -clock CLK  -min -0.1  [get_ports {gpio_pad[3]}]
set_output_delay -clock CLK  -max 20  [get_ports {gpio_pad[2]}]
set_output_delay -clock CLK  -min -0.1  [get_ports {gpio_pad[2]}]
set_output_delay -clock CLK  -max 20  [get_ports {gpio_pad[1]}]
set_output_delay -clock CLK  -min -0.1  [get_ports {gpio_pad[1]}]
set_output_delay -clock CLK  -max 20  [get_ports {gpio_pad[0]}]
set_output_delay -clock CLK  -min -0.1  [get_ports {gpio_pad[0]}]
